
# This file is automatically generated, you probably don't want to edit this

r2rOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "r2rOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            rvalue = 0,
            DVsd = 0, ...) {

            super$initialize(
                package="D2R",
                name="r2r",
                requiresData=FALSE,
                ...)

            private$..rvalue <- jmvcore::OptionNumber$new(
                "rvalue",
                rvalue,
                default=0)
            private$..DVsd <- jmvcore::OptionNumber$new(
                "DVsd",
                DVsd,
                default=0)

            self$.addOption(private$..rvalue)
            self$.addOption(private$..DVsd)
        }),
    active = list(
        rvalue = function() private$..rvalue$value,
        DVsd = function() private$..DVsd$value),
    private = list(
        ..rvalue = NA,
        ..DVsd = NA)
)

r2rResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "r2rResults",
    inherit = jmvcore::Group,
    active = list(
        reportTable = function() private$.items[["reportTable"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="correlation to r")
            self$add(jmvcore::Table$new(
                options=options,
                name="reportTable",
                title=" ",
                rows=8,
                columns=list(
                    list(
                        `name`="Parameter", 
                        `type`="text"),
                    list(
                        `name`="Value", 
                        `type`="number"))))}))

r2rBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "r2rBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "D2R",
                name = "r2r",
                version = c(1,0,0),
                options = options,
                results = r2rResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' correlation to r
#'
#' 
#' @param rvalue .
#' @param DVsd .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$reportTable} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$reportTable$asDF}
#'
#' \code{as.data.frame(results$reportTable)}
#'
#' @export
r2r <- function(
    rvalue = 0,
    DVsd = 0) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("r2r requires jmvcore to be installed (restart may be required)")


    options <- r2rOptions$new(
        rvalue = rvalue,
        DVsd = DVsd)

    analysis <- r2rClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

